# Generated by Django 4.1.7 on 2023-03-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='contact',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='details',
            name='email',
            field=models.TextField(),
        ),
    ]
